#pragma once

#include <torch/torch.h>

#include <core/DerivedTypes.hpp>

namespace common {

/*
 * SymmetryTransform's provide a mechanism to effectively apply a symmetry transform to a GameState. In the game of go,
 * there are 8 transforms: 4 rotations and 4 reflections. See AlphaGo papers for more details.
 */
template<typename GameState, typename Tensorizor>
class AbstractSymmetryTransform {
public:
  using InputTensor = typename TensorizorTypes<Tensorizor>::InputTensor;
  using PolicyTensor = typename GameStateTypes<GameState>::PolicyTensor;

  virtual ~AbstractSymmetryTransform() {}

  /*
   * Transforms a tensor generated by a Tensorizor in place.
   */
  virtual void transform_input(InputTensor& input) = 0;

  /*
   * Transforms a policy tensor in place.
   */
  virtual void transform_policy(PolicyTensor& policy) = 0;
};

}  // namespace common
