// Auto-generated by py/carassonne/lookup_tables_writer.py
#include <games/carcassonne/LookupTables.hpp>

namespace carcassonne {

const uint32_t kValidOrientationTable[4] = {
  0x00ffffff,  // dN
  0x007bfffe,  // dE
  0x005be3fe,  // dS
  0x005be3fe   // dW
};

const uint8_t kEdgeProfileTable[4 * kNumTileTypes] = {
  0xff,  // tCCCC110 dN -> CCCC
  0xff,  // tCCCC110 dE -> CCCC (invalid)
  0xff,  // tCCCC110 dS -> CCCC (invalid)
  0xff,  // tCCCC110 dW -> CCCC (invalid)
  0xfd,  // tCCCF100 dN -> CCCF
  0x7f,  // tCCCF100 dE -> FCCC
  0xdf,  // tCCCF100 dS -> CFCC
  0xf7,  // tCCCF100 dW -> CCFC
  0xfd,  // tCCCF110 dN -> CCCF
  0x7f,  // tCCCF110 dE -> FCCC
  0xdf,  // tCCCF110 dS -> CFCC
  0xf7,  // tCCCF110 dW -> CCFC
  0xfe,  // tCCCR100 dN -> CCCR
  0xbf,  // tCCCR100 dE -> RCCC
  0xef,  // tCCCR100 dS -> CRCC
  0xfb,  // tCCCR100 dW -> CCRC
  0xfe,  // tCCCR110 dN -> CCCR
  0xbf,  // tCCCR110 dE -> RCCC
  0xef,  // tCCCR110 dS -> CRCC
  0xfb,  // tCCCR110 dW -> CCRC
  0xf5,  // tCCFF100 dN -> CCFF
  0x7d,  // tCCFF100 dE -> FCCF
  0x5f,  // tCCFF100 dS -> FFCC
  0xd7,  // tCCFF100 dW -> CFFC
  0xf5,  // tCCFF110 dN -> CCFF
  0x7d,  // tCCFF110 dE -> FCCF
  0x5f,  // tCCFF110 dS -> FFCC
  0xd7,  // tCCFF110 dW -> CFFC
  0xf5,  // tCCFF200 dN -> CCFF
  0x7d,  // tCCFF200 dE -> FCCF
  0x5f,  // tCCFF200 dS -> FFCC
  0xd7,  // tCCFF200 dW -> CFFC
  0xfa,  // tCCRR100 dN -> CCRR
  0xbe,  // tCCRR100 dE -> RCCR
  0xaf,  // tCCRR100 dS -> RRCC
  0xeb,  // tCCRR100 dW -> CRRC
  0xfa,  // tCCRR110 dN -> CCRR
  0xbe,  // tCCRR110 dE -> RCCR
  0xaf,  // tCCRR110 dS -> RRCC
  0xeb,  // tCCRR110 dW -> CRRC
  0xdd,  // tCFCF100 dN -> CFCF
  0x77,  // tCFCF100 dE -> FCFC
  0xdd,  // tCFCF100 dS -> CFCF (invalid)
  0x77,  // tCFCF100 dW -> FCFC (invalid)
  0xdd,  // tCFCF110 dN -> CFCF
  0x77,  // tCFCF110 dE -> FCFC
  0xdd,  // tCFCF110 dS -> CFCF (invalid)
  0x77,  // tCFCF110 dW -> FCFC (invalid)
  0xdd,  // tCFCF200 dN -> CFCF
  0x77,  // tCFCF200 dE -> FCFC
  0xdd,  // tCFCF200 dS -> CFCF (invalid)
  0x77,  // tCFCF200 dW -> FCFC (invalid)
  0xd5,  // tCFFF100 dN -> CFFF
  0x75,  // tCFFF100 dE -> FCFF
  0x5d,  // tCFFF100 dS -> FFCF
  0x57,  // tCFFF100 dW -> FFFC
  0xda,  // tCFRR100 dN -> CFRR
  0xb6,  // tCFRR100 dE -> RCFR
  0xad,  // tCFRR100 dS -> RRCF
  0x6b,  // tCFRR100 dW -> FRRC
  0xe6,  // tCRFR100 dN -> CRFR
  0xb9,  // tCRFR100 dE -> RCRF
  0x6e,  // tCRFR100 dS -> FRCR
  0x9b,  // tCRFR100 dW -> RFRC
  0xe9,  // tCRRF100 dN -> CRRF
  0x7a,  // tCRRF100 dE -> FCRR
  0x9e,  // tCRRF100 dS -> RFCR
  0xa7,  // tCRRF100 dW -> RRFC
  0xea,  // tCRRR100 dN -> CRRR
  0xba,  // tCRRR100 dE -> RCRR
  0xae,  // tCRRR100 dS -> RRCR
  0xab,  // tCRRR100 dW -> RRRC
  0x55,  // tFFFF001 dN -> FFFF
  0x55,  // tFFFF001 dE -> FFFF (invalid)
  0x55,  // tFFFF001 dS -> FFFF (invalid)
  0x55,  // tFFFF001 dW -> FFFF (invalid)
  0x56,  // tFFFR001 dN -> FFFR
  0x95,  // tFFFR001 dE -> RFFF
  0x65,  // tFFFR001 dS -> FRFF
  0x59,  // tFFFR001 dW -> FFRF
  0x5a,  // tFFRR000 dN -> FFRR
  0x96,  // tFFRR000 dE -> RFFR
  0xa5,  // tFFRR000 dS -> RRFF
  0x69,  // tFFRR000 dW -> FRRF
  0x66,  // tFRFR000 dN -> FRFR
  0x99,  // tFRFR000 dE -> RFRF
  0x66,  // tFRFR000 dS -> FRFR (invalid)
  0x99,  // tFRFR000 dW -> RFRF (invalid)
  0x6a,  // tFRRR000 dN -> FRRR
  0x9a,  // tFRRR000 dE -> RFRR
  0xa6,  // tFRRR000 dS -> RRFR
  0xa9,  // tFRRR000 dW -> RRRF
  0xaa,  // tRRRR000 dN -> RRRR
  0xaa,  // tRRRR000 dE -> RRRR (invalid)
  0xaa,  // tRRRR000 dS -> RRRR (invalid)
  0xaa   // tRRRR000 dW -> RRRR (invalid)
};

const uint8_t kMeepleLocationProfileTable[4 * kNumTileTypes] = {
  0x01,  // tCCCC110 dN -> CCCC
  0x02,  // tCCCC110 dE -> CCCC (invalid)
  0x04,  // tCCCC110 dS -> CCCC (invalid)
  0x08,  // tCCCC110 dW -> CCCC (invalid)
  0x41,  // tCCCF100 dN -> CCCF
  0x82,  // tCCCF100 dE -> FCCC
  0x14,  // tCCCF100 dS -> CFCC
  0x28,  // tCCCF100 dW -> CCFC
  0x41,  // tCCCF110 dN -> CCCF
  0x82,  // tCCCF110 dE -> FCCC
  0x14,  // tCCCF110 dS -> CFCC
  0x28,  // tCCCF110 dW -> CCFC
  0xc9,  // tCCCR100 dN -> CCCR
  0x93,  // tCCCR100 dE -> RCCC
  0x36,  // tCCCR100 dS -> CRCC
  0x6c,  // tCCCR100 dW -> CCRC
  0xc9,  // tCCCR110 dN -> CCCR
  0x93,  // tCCCR110 dE -> RCCC
  0x36,  // tCCCR110 dS -> CRCC
  0x6c,  // tCCCR110 dW -> CCRC
  0x21,  // tCCFF100 dN -> CCFF
  0x42,  // tCCFF100 dE -> FCCF
  0x84,  // tCCFF100 dS -> FFCC
  0x18,  // tCCFF100 dW -> CFFC
  0x21,  // tCCFF110 dN -> CCFF
  0x42,  // tCCFF110 dE -> FCCF
  0x84,  // tCCFF110 dS -> FFCC
  0x18,  // tCCFF110 dW -> CFFC
  0x13,  // tCCFF200 dN -> CCFF
  0x26,  // tCCFF200 dE -> FCCF
  0x4c,  // tCCFF200 dS -> FFCC
  0x89,  // tCCFF200 dW -> CFFC
  0x65,  // tCCRR100 dN -> CCRR
  0xca,  // tCCRR100 dE -> RCCR
  0x95,  // tCCRR100 dS -> RRCC
  0x3a,  // tCCRR100 dW -> CRRC
  0x65,  // tCCRR110 dN -> CCRR
  0xca,  // tCCRR110 dE -> RCCR
  0x95,  // tCCRR110 dS -> RRCC
  0x3a,  // tCCRR110 dW -> CRRC
  0x51,  // tCFCF100 dN -> CFCF
  0xa2,  // tCFCF100 dE -> FCFC
  0x54,  // tCFCF100 dS -> CFCF (invalid)
  0xa8,  // tCFCF100 dW -> FCFC (invalid)
  0x51,  // tCFCF110 dN -> CFCF
  0xa2,  // tCFCF110 dE -> FCFC
  0x54,  // tCFCF110 dS -> CFCF (invalid)
  0xa8,  // tCFCF110 dW -> FCFC (invalid)
  0x15,  // tCFCF200 dN -> CFCF
  0x2a,  // tCFCF200 dE -> FCFC
  0x45,  // tCFCF200 dS -> CFCF (invalid)
  0x8a,  // tCFCF200 dW -> FCFC (invalid)
  0x11,  // tCFFF100 dN -> CFFF
  0x22,  // tCFFF100 dE -> FCFF
  0x44,  // tCFFF100 dS -> FFCF
  0x88,  // tCFFF100 dW -> FFFC
  0x55,  // tCFRR100 dN -> CFRR
  0xaa,  // tCFRR100 dE -> RCFR
  0x55,  // tCFRR100 dS -> RRCF
  0xaa,  // tCFRR100 dW -> FRRC
  0x33,  // tCRFR100 dN -> CRFR
  0x66,  // tCRFR100 dE -> RCRF
  0xcc,  // tCRFR100 dS -> FRCR
  0x99,  // tCRFR100 dW -> RFRC
  0x33,  // tCRRF100 dN -> CRRF
  0x66,  // tCRRF100 dE -> FCRR
  0xcc,  // tCRRF100 dS -> RFCR
  0x99,  // tCRRF100 dW -> RRFC
  0x7f,  // tCRRR100 dN -> CRRR
  0xef,  // tCRRR100 dE -> RCRR
  0xdf,  // tCRRR100 dS -> RRCR
  0xbf,  // tCRRR100 dW -> RRRC
  0x10,  // tFFFF001 dN -> FFFF
  0x20,  // tFFFF001 dE -> FFFF (invalid)
  0x40,  // tFFFF001 dS -> FFFF (invalid)
  0x80,  // tFFFF001 dW -> FFFF (invalid)
  0x18,  // tFFFR001 dN -> FFFR
  0x21,  // tFFFR001 dE -> RFFF
  0x42,  // tFFFR001 dS -> FRFF
  0x84,  // tFFFR001 dW -> FFRF
  0x54,  // tFFRR000 dN -> FFRR
  0xa8,  // tFFRR000 dE -> RFFR
  0x51,  // tFFRR000 dS -> RRFF
  0xa2,  // tFFRR000 dW -> FRRF
  0x32,  // tFRFR000 dN -> FRFR
  0x64,  // tFRFR000 dE -> RFRF
  0xc8,  // tFRFR000 dS -> FRFR (invalid)
  0x91,  // tFRFR000 dW -> RFRF (invalid)
  0x7e,  // tFRRR000 dN -> FRRR
  0xed,  // tFRRR000 dE -> RFRR
  0xdb,  // tFRRR000 dS -> RRFR
  0xb7,  // tFRRR000 dW -> RRRF
  0xff,  // tRRRR000 dN -> RRRR
  0xff,  // tRRRR000 dE -> RRRR (invalid)
  0xff,  // tRRRR000 dS -> RRRR (invalid)
  0xff   // tRRRR000 dW -> RRRR (invalid)
};

}  // namespace carcassonne

