#pragma once

#include "core/concepts/TensorEncodingsConcept.hpp"
#include "util/EigenUtil.hpp"
#include "util/MetaProgramming.hpp"

namespace core {

template <core::concepts::TensorEncodings TensorEncodings>
struct PolicyTarget {
  static constexpr char kName[] = "policy";
  using PolicyEncoding = TensorEncodings::PolicyEncoding;
  using Tensor = PolicyEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// NOTE: If we add a game where we produce non-logit value predictions, we should modify this to
// allow customization. We will likely need this in single-player games.
template <core::concepts::TensorEncodings TensorEncodings>
struct ValueTarget {
  static constexpr char kName[] = "value";
  using GameResultEncoding = TensorEncodings::GameResultEncoding;
  using Tensor = GameResultEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// ActionValueTarget is generated by evaluating the Value head on the states that result from taking
// each action from the current position.
template <core::concepts::TensorEncodings TensorEncodings>
struct ActionValueTarget {
  static constexpr char kName[] = "action_value";
  using Tensor = TensorEncodings::ActionValueEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// future_mcts_value is the lambda-discounted sum of future Q_root values, computed retroactively
// in GameWriteLog::add_terminal(). This is used to compute the training target for the U head.
template <core::concepts::TensorEncodings TensorEncodings>
struct FutureMCTSValueTarget {
  static constexpr char kName[] = "future_mcts_value";
  using Tensor = TensorEncodings::WinShareTensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// ActionValueUncertaintyTarget is generated by evaluating the ValueUncertainty head on the states
// that result from taking each action from the current position.
template <core::concepts::TensorEncodings TensorEncodings>
struct ActionValueUncertaintyTarget {
  static constexpr char kName[] = "action_value_uncertainty";
  using Tensor = TensorEncodings::ActionValueEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

template <core::concepts::TensorEncodings TensorEncodings>
struct OppPolicyTarget {
  using PolicyEncoding = TensorEncodings::PolicyEncoding;
  static constexpr char kName[] = "opp_policy";
  using Tensor = PolicyEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// Qs_star and Ws_star: the prior-augmented children-average baselines (LoTE/LoTV) at the root
// captured at search time, as scalars from the root's active-seat perspective (the trailing
// 's' stands for 'seat'). These are recorded into the game log so that BackupNet sees the same
// baselines training-time as it would have seen at search-time — see docs/BetaZero.pdf and
// beta0::BackupSampleData.
template <core::concepts::TensorEncodings TensorEncodings>
struct QsStarTarget {
  static constexpr char kName[] = "Qs_star";
  using Tensor = eigen_util::FTensor<Eigen::Sizes<1>>;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

template <core::concepts::TensorEncodings TensorEncodings>
struct WsStarTarget {
  static constexpr char kName[] = "Ws_star";
  using Tensor = eigen_util::FTensor<Eigen::Sizes<1>>;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

namespace alpha0 {

template <core::concepts::TensorEncodings TensorEncodings>
struct StandardTrainingTargets {
  using Game = TensorEncodings::Game;
  using PolicyTarget = core::PolicyTarget<TensorEncodings>;
  using ValueTarget = core::ValueTarget<TensorEncodings>;
  using ActionValueTarget = core::ActionValueTarget<TensorEncodings>;
  using OppPolicyTarget = core::OppPolicyTarget<TensorEncodings>;

  using List = mp::TypeList<PolicyTarget, ValueTarget, ActionValueTarget, OppPolicyTarget>;
};

template <core::concepts::TensorEncodings TensorEncodings>
using StandardTrainingTargetsList = typename StandardTrainingTargets<TensorEncodings>::List;

}  // namespace alpha0

namespace beta0 {

template <core::concepts::TensorEncodings TensorEncodings>
struct StandardTrainingTargets {
  using Game = TensorEncodings::Game;
  using PolicyTarget = core::PolicyTarget<TensorEncodings>;
  using ValueTarget = core::ValueTarget<TensorEncodings>;
  using ActionValueTarget = core::ActionValueTarget<TensorEncodings>;
  using FutureMCTSValueTarget = core::FutureMCTSValueTarget<TensorEncodings>;
  using ActionValueUncertaintyTarget = core::ActionValueUncertaintyTarget<TensorEncodings>;
  using OppPolicyTarget = core::OppPolicyTarget<TensorEncodings>;
  using QsStarTarget = core::QsStarTarget<TensorEncodings>;
  using WsStarTarget = core::WsStarTarget<TensorEncodings>;

  // TODO: BackupLossTerm will consume Qs_star, Ws_star, and a child-stats target as
  // model inputs (see docs/BetaZero.pdf and py/games/connect4/spec.py).

  using List = mp::TypeList<PolicyTarget, ValueTarget, ActionValueTarget, FutureMCTSValueTarget,
                            ActionValueUncertaintyTarget, OppPolicyTarget, QsStarTarget,
                            WsStarTarget>;
};

template <core::concepts::TensorEncodings TensorEncodings>
using StandardTrainingTargetsList = typename StandardTrainingTargets<TensorEncodings>::List;

}  // namespace beta0

}  // namespace core

#include "inline/core/TrainingTargets.inl"
