#pragma once

#include "core/concepts/TensorEncodingsConcept.hpp"
#include "util/MetaProgramming.hpp"

namespace core {

template <core::concepts::TensorEncodings TensorEncodings>
struct PolicyTarget {
  static constexpr char kName[] = "policy";
  using PolicyEncoding = TensorEncodings::PolicyEncoding;
  using Tensor = PolicyEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// NOTE: If we add a game where we produce non-logit value predictions, we should modify this to
// allow customization. We will likely need this in single-player games.
template <core::concepts::TensorEncodings TensorEncodings>
struct ValueTarget {
  static constexpr char kName[] = "value";
  using GameResultEncoding = TensorEncodings::GameResultEncoding;
  using Tensor = GameResultEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// ActionValueTarget is generated by evaluating the Value head on the states that result from taking
// each action from the current position.
template <core::concepts::TensorEncodings TensorEncodings>
struct ActionValueTarget {
  static constexpr char kName[] = "action_value";
  using Tensor = TensorEncodings::ActionValueEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// QTarget is used to train the ValueUncertainty head, which predicts the squared
// difference between Q prior and Q posterior.
//
// We could compute this squared difference directly and export it as a target, but we instead
// follow the example of KataGo and export Q posterior itself as a target, and let the
// ValueUncertainty head compute the squared difference based on the output of the Value head
// (which represents the Q prior).
//
// ACTUALLY...to make the U head conservative, instead of using (Q_initial - Q_final)^2 as the
// target, we use max((Q_initial - Q_min)^2, (Q_max - Q_initial)^2, W_final), where Q_min and Q_max
// are the min and max Q values at this node throughout search, and where W_final is the final
// uncertainty value. This encourages the U head to overestimate uncertainty.
template <core::concepts::TensorEncodings TensorEncodings>
struct QTarget {
  static constexpr char kName[] = "Q";
  using Tensor = TensorEncodings::WinShareTensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// QMinTarget is used to train the ValueUncertainty head.
//
// See comments on QTarget.
template <core::concepts::TensorEncodings TensorEncodings>
struct QMinTarget {
  static constexpr char kName[] = "Q_min";
  using Tensor = TensorEncodings::WinShareTensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// QMaxTarget is used to train the ValueUncertainty head.
//
// See comments on QTarget.
template <core::concepts::TensorEncodings TensorEncodings>
struct QMaxTarget {
  static constexpr char kName[] = "Q_max";
  using Tensor = TensorEncodings::WinShareTensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// WTarget is used to train the ValueUncertainty head.
//
// See comments on QTarget.
template <core::concepts::TensorEncodings TensorEncodings>
struct WTarget {
  static constexpr char kName[] = "W";
  using Tensor = TensorEncodings::WinShareTensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// ActionValueUncertaintyTarget is generated by evaluating the ValueUncertainty head on the states
// that result from taking each action from the current position.
template <core::concepts::TensorEncodings TensorEncodings>
struct ActionValueUncertaintyTarget {
  static constexpr char kName[] = "action_value_uncertainty";
  using Tensor = TensorEncodings::ActionValueEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

template <core::concepts::TensorEncodings TensorEncodings>
struct OppPolicyTarget {
  using PolicyEncoding = TensorEncodings::PolicyEncoding;
  static constexpr char kName[] = "opp_policy";
  using Tensor = PolicyEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

namespace alpha0 {

template <core::concepts::TensorEncodings TensorEncodings>
struct StandardTrainingTargets {
  using Game = TensorEncodings::Game;
  using PolicyTarget = core::PolicyTarget<TensorEncodings>;
  using ValueTarget = core::ValueTarget<TensorEncodings>;
  using ActionValueTarget = core::ActionValueTarget<TensorEncodings>;
  using OppPolicyTarget = core::OppPolicyTarget<TensorEncodings>;

  using List = mp::TypeList<PolicyTarget, ValueTarget, ActionValueTarget, OppPolicyTarget>;
};

template <core::concepts::TensorEncodings TensorEncodings>
using StandardTrainingTargetsList = typename StandardTrainingTargets<TensorEncodings>::List;

}  // namespace alpha0

}  // namespace core

#include "inline/core/TrainingTargets.inl"
