#pragma once

#include "core/concepts/TensorEncodingsConcept.hpp"
#include "util/MetaProgramming.hpp"

namespace core {

template <core::concepts::TensorEncodings TensorEncodings>
struct PolicyTarget {
  static constexpr char kName[] = "policy";
  using PolicyEncoding = TensorEncodings::PolicyEncoding;
  using Tensor = PolicyEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// NOTE: If we add a game where we produce non-logit value predictions, we should modify this to
// allow customization. We will likely need this in single-player games.
template <core::concepts::TensorEncodings TensorEncodings>
struct ValueTarget {
  static constexpr char kName[] = "value";
  using GameResultEncoding = TensorEncodings::GameResultEncoding;
  using Tensor = GameResultEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// ActionValueTarget is generated by evaluating the Value head on the states that result from taking
// each action from the current position.
template <core::concepts::TensorEncodings TensorEncodings>
struct ActionValueTarget {
  static constexpr char kName[] = "action_value";
  using Tensor = TensorEncodings::ActionValueEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

template <core::concepts::TensorEncodings TensorEncodings>
struct QStarTarget {
  static constexpr char kName[] = "Q_star";
  using Tensor = TensorEncodings::WinShareTensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

// ActionValueUncertaintyTarget is generated by evaluating the ValueUncertainty head on the states
// that result from taking each action from the current position.
template <core::concepts::TensorEncodings TensorEncodings>
struct ActionValueUncertaintyTarget {
  static constexpr char kName[] = "action_value_uncertainty";
  using Tensor = TensorEncodings::ActionValueEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

template <core::concepts::TensorEncodings TensorEncodings>
struct OppPolicyTarget {
  using PolicyEncoding = TensorEncodings::PolicyEncoding;
  static constexpr char kName[] = "opp_policy";
  using Tensor = PolicyEncoding::Tensor;

  template <typename GameLogView>
  static bool encode(const GameLogView& view, Tensor&);
};

namespace alpha0 {

template <core::concepts::TensorEncodings TensorEncodings>
struct StandardTrainingTargets {
  using Game = TensorEncodings::Game;
  using PolicyTarget = core::PolicyTarget<TensorEncodings>;
  using ValueTarget = core::ValueTarget<TensorEncodings>;
  using ActionValueTarget = core::ActionValueTarget<TensorEncodings>;
  using OppPolicyTarget = core::OppPolicyTarget<TensorEncodings>;

  using List = mp::TypeList<PolicyTarget, ValueTarget, ActionValueTarget, OppPolicyTarget>;
};

template <core::concepts::TensorEncodings TensorEncodings>
using StandardTrainingTargetsList = typename StandardTrainingTargets<TensorEncodings>::List;

}  // namespace alpha0

namespace beta0 {

template <core::concepts::TensorEncodings TensorEncodings>
struct StandardTrainingTargets {
  using Game = TensorEncodings::Game;
  using PolicyTarget = core::PolicyTarget<TensorEncodings>;
  using ValueTarget = core::ValueTarget<TensorEncodings>;
  using ActionValueTarget = core::ActionValueTarget<TensorEncodings>;
  using QStarTarget = core::QStarTarget<TensorEncodings>;
  using ActionValueUncertaintyTarget = core::ActionValueUncertaintyTarget<TensorEncodings>;
  using OppPolicyTarget = core::OppPolicyTarget<TensorEncodings>;

  using List = mp::TypeList<PolicyTarget, ValueTarget, ActionValueTarget, QStarTarget,
                            ActionValueUncertaintyTarget, OppPolicyTarget>;
};

template <core::concepts::TensorEncodings TensorEncodings>
using StandardTrainingTargetsList = typename StandardTrainingTargets<TensorEncodings>::List;

}  // namespace beta0

}  // namespace core

#include "inline/core/TrainingTargets.inl"
