/*
 * Equivalence tests: C++ BackupNNEvaluator vs. Python BackupNet.
 *
 * Loads:
 *   * test_models/beta0_backup_nn_test.onnx               (Python-exported ONNX with nnue prefix)
 *   * goldenfiles/beta0_tests/backup_nn_equivalence.json  (Python reference outputs)
 *
 * Both files are regenerated by:
 *   python py/tests/shared/gen_backup_nn_goldenfile.py
 *
 * Tests:
 *   1. MatchesPythonReference: For each round in the goldenfile, recompute embeddings
 *      from scratch, sum them into the accumulator, then run apply(); compare against
 *      the Python reference values.
 *   2. IncrementalUpdateMatchesFullRecompute: Maintain the accumulator incrementally
 *      across rounds (subtract old embedding, add new one) — this is the invariant
 *      that beta0::Manager::update_stats relies on. Verify the result matches the
 *      full-recompute path round by round.
 */

#include "beta0/BackupNNEvaluator.hpp"
#include "core/ModelBundle.hpp"
#include "core/SpecTransforms.hpp"
#include "games/connect4/Bindings.hpp"
#include "util/GTestUtil.hpp"
#include "util/RepoUtil.hpp"

#include <boost/filesystem.hpp>
#include <boost/json.hpp>
#include <gtest/gtest.h>

#include <cstring>
#include <fstream>
#include <iterator>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#ifndef MIT_TEST_MODE
static_assert(false, "MIT_TEST_MODE macro must be defined for unit tests");
#endif

namespace {

using TestSpec = transforms::AddStateStorage<c4::beta0::Spec>;
using BNN = beta0::BackupNNEvaluator<TestSpec>;
using ChildStatArray = BNN::ChildStatArray;
using ActionLatentArray = BNN::ActionLatentArray;
using EmbedArray = BNN::EmbedArray;
using AccumulatorArray = BNN::AccumulatorArray;
using StaticLatentArray = BNN::StaticLatentArray;
using GameResultTensor = BNN::Tensor;

constexpr float kFloatTol = 1e-5f;

std::shared_ptr<const std::vector<char>> read_file_bytes(const boost::filesystem::path& path) {
  std::ifstream in(path.string(), std::ios::binary);
  RELEASE_ASSERT(in.is_open(), "Could not open {}", path.string());
  auto buf = std::make_shared<std::vector<char>>((std::istreambuf_iterator<char>(in)),
                                                 std::istreambuf_iterator<char>());
  return buf;
}

std::string read_file_str(const boost::filesystem::path& path) {
  std::ifstream in(path.string());
  RELEASE_ASSERT(in.is_open(), "Could not open {}", path.string());
  std::stringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

// Convert a boost::json::array of doubles into a fixed-size Eigen array.
template <int N>
Eigen::Array<float, N, 1> json_to_array(const boost::json::array& arr) {
  RELEASE_ASSERT((int)arr.size() == N, "json array size {} != expected {}", arr.size(), N);
  Eigen::Array<float, N, 1> out;
  for (int i = 0; i < N; ++i) {
    out(i) = static_cast<float>(arr[i].as_double());
  }
  return out;
}

// Load (model_bundle, parsed_json) from disk once per test program.
struct Fixture {
  core::ModelBundle bundle;
  boost::json::value json_root;
  StaticLatentArray z_s;
  std::vector<ActionLatentArray> action_latent;  // size num_actions
  GameResultTensor S_baseline;
  float Ws_baseline;
  int num_actions;
  int num_rounds;

  static const Fixture& instance() {
    static Fixture f = []() {
      Fixture g;
      auto root = util::Repo::root();
      boost::filesystem::path onnx_path = root / "test_models" / "beta0_backup_nn_test.onnx";
      boost::filesystem::path json_path =
        root / "goldenfiles" / "beta0_tests" / "backup_nn_equivalence.json";

      auto raw = read_file_bytes(onnx_path);
      RELEASE_ASSERT(core::parse_model_bundle(raw, g.bundle), "parse_model_bundle failed");

      g.json_root = boost::json::parse(read_file_str(json_path));
      const auto& obj = g.json_root.as_object();

      // Sanity-check the dimensions encoded in the JSON match this build's c4::beta0::Spec.
      RELEASE_ASSERT(obj.at("static_latent_dim").as_int64() == BNN::kStaticLatentDim,
                     "goldenfile static_latent_dim mismatch");
      RELEASE_ASSERT(obj.at("embed_dim").as_int64() == BNN::kEmbedDim,
                     "goldenfile embed_dim mismatch");
      RELEASE_ASSERT(obj.at("action_latent_dim").as_int64() == BNN::kActionLatentDim,
                     "goldenfile action_latent_dim mismatch");
      RELEASE_ASSERT(obj.at("value_dim").as_int64() == BNN::kValueDim,
                     "goldenfile value_dim mismatch");

      g.num_actions = (int)obj.at("num_actions").as_int64();
      g.z_s = json_to_array<BNN::kStaticLatentDim>(obj.at("z_s").as_array());
      auto Ss_arr = json_to_array<BNN::kValueDim>(obj.at("value_baseline").as_array());
      for (int i = 0; i < BNN::kValueDim; ++i) g.S_baseline(i) = Ss_arr(i);
      g.Ws_baseline = (float)obj.at("value_uncertainty_baseline").as_double();

      const auto& za_arr = obj.at("action_latent").as_array();
      RELEASE_ASSERT((int)za_arr.size() == g.num_actions, "action_latent size mismatch");
      for (int i = 0; i < g.num_actions; ++i) {
        g.action_latent.push_back(json_to_array<BNN::kActionLatentDim>(za_arr[i].as_array()));
      }

      g.num_rounds = (int)obj.at("rounds").as_array().size();
      return g;
    }();
    return f;
  }
};

ChildStatArray load_child_stats(const boost::json::array& row) {
  return json_to_array<BNN::kChildStatDim>(row);
}

}  // namespace

TEST(BackupNNEquivalence, MatchesPythonReference) {
  const Fixture& f = Fixture::instance();
  BNN evaluator;
  evaluator.reload_weights(f.bundle);
  ASSERT_TRUE(evaluator.ready());

  const auto& rounds = f.json_root.as_object().at("rounds").as_array();

  for (int r = 0; r < f.num_rounds; ++r) {
    SCOPED_TRACE("round " + std::to_string(r));
    const auto& round_obj = rounds[r].as_object();
    const auto& cs_rows = round_obj.at("child_stats").as_array();
    const auto& expected_emb = round_obj.at("expected_embeddings").as_array();
    const auto& expected_acc = round_obj.at("expected_accumulator").as_array();
    auto expected_S = json_to_array<BNN::kValueDim>(round_obj.at("expected_S").as_array());
    float expected_W = (float)round_obj.at("expected_W").as_double();

    AccumulatorArray acc;
    acc.setZero();
    for (int i = 0; i < f.num_actions; ++i) {
      ChildStatArray cs = load_child_stats(cs_rows[i].as_array());
      EmbedArray e = evaluator.compute_child_embedding(cs, f.action_latent[i]);
      EmbedArray ref = json_to_array<BNN::kEmbedDim>(expected_emb[i].as_array());
      for (int j = 0; j < BNN::kEmbedDim; ++j) {
        EXPECT_NEAR(e(j), ref(j), kFloatTol) << "embedding[" << i << "][" << j << "]";
      }
      acc += e;
    }

    AccumulatorArray ref_acc = json_to_array<BNN::kEmbedDim>(expected_acc);
    for (int j = 0; j < BNN::kEmbedDim; ++j) {
      EXPECT_NEAR(acc(j), ref_acc(j), kFloatTol) << "accumulator[" << j << "]";
    }

    auto sw = evaluator.apply(acc, f.z_s, f.S_baseline, f.Ws_baseline);
    for (int i = 0; i < BNN::kValueDim; ++i) {
      EXPECT_NEAR(sw.S(i), expected_S(i), kFloatTol) << "S[" << i << "]";
    }
    EXPECT_NEAR(sw.W, expected_W, kFloatTol);
  }
}

TEST(BackupNNEquivalence, IncrementalUpdateMatchesFullRecompute) {
  const Fixture& f = Fixture::instance();
  BNN evaluator;
  evaluator.reload_weights(f.bundle);
  ASSERT_TRUE(evaluator.ready());

  const auto& rounds = f.json_root.as_object().at("rounds").as_array();

  // Maintain (a) a per-action cache of the most recent embeddings, and (b) an accumulator
  // that we update incrementally via subtract-add (the invariant Manager::update_stats relies
  // on). Compare to the per-round full-recompute results.
  std::vector<EmbedArray> cached_emb(f.num_actions);
  for (auto& e : cached_emb) e.setZero();
  AccumulatorArray inc_acc;
  inc_acc.setZero();

  for (int r = 0; r < f.num_rounds; ++r) {
    SCOPED_TRACE("round " + std::to_string(r));
    const auto& round_obj = rounds[r].as_object();
    const auto& cs_rows = round_obj.at("child_stats").as_array();

    // Full recompute path.
    AccumulatorArray full_acc;
    full_acc.setZero();
    std::vector<EmbedArray> full_emb(f.num_actions);
    for (int i = 0; i < f.num_actions; ++i) {
      ChildStatArray cs = load_child_stats(cs_rows[i].as_array());
      full_emb[i] = evaluator.compute_child_embedding(cs, f.action_latent[i]);
      full_acc += full_emb[i];
    }

    // Incremental subtract-add path.
    for (int i = 0; i < f.num_actions; ++i) {
      ChildStatArray cs = load_child_stats(cs_rows[i].as_array());
      EmbedArray new_e = evaluator.compute_child_embedding(cs, f.action_latent[i]);
      inc_acc -= cached_emb[i];
      inc_acc += new_e;
      cached_emb[i] = new_e;
    }

    for (int j = 0; j < BNN::kEmbedDim; ++j) {
      EXPECT_NEAR(inc_acc(j), full_acc(j), kFloatTol)
        << "incremental vs full accumulator mismatch at j=" << j;
    }

    auto sw_full = evaluator.apply(full_acc, f.z_s, f.S_baseline, f.Ws_baseline);
    auto sw_inc = evaluator.apply(inc_acc, f.z_s, f.S_baseline, f.Ws_baseline);
    for (int i = 0; i < BNN::kValueDim; ++i) {
      EXPECT_NEAR(sw_inc.S(i), sw_full.S(i), kFloatTol);
    }
    EXPECT_NEAR(sw_inc.W, sw_full.W, kFloatTol);
  }
}

int main(int argc, char** argv) { return launch_gtest(argc, argv); }
