import games.index as game_index
from util.py_util import is_valid_path_component

import argparse
from dataclasses import dataclass
import os
import sys
from typing import List


@dataclass
class RunParams:
    """
    Parameters used to specify a particular AlphaZero run. All files generated by the run are
    written to:

        {output_dir}/{game}/{tag}/

    according to the directory structure described in DirectoryOrganizer.
    """
    output_dir: str
    game: str
    tag: str

    def __post_init__(self):
        self.validate()

    @staticmethod
    def create(args) -> 'RunParams':
        return RunParams(
            output_dir=args.output_dir,
            game=args.game,
            tag=args.tag,
        )

    def validate(self):
        assert self.game, 'Required option: --game/-g'
        assert self.tag, 'Required option: --tag/-t'

        assert game_index.is_valid_game_name(self.game), f'Invalid game name: {self.game}'
        assert self.tag.find('@') == -1, 'Tag cannot contain @'
        assert is_valid_path_component(self.tag), f'Illegal tag name: {self.tag}'

    @staticmethod
    def add_args(parser: argparse.ArgumentParser, multiple_tags=False):
        group = parser.add_argument_group('Common options')

        env_var = 'A0A_OUTPUT_DIR'
        default_output_dir = os.environ.get(env_var, None)
        if default_output_dir is None:
            print(f'Environment variable {env_var} is not set. Please run "source env_setup.sh" from repo root.')
            sys.exit(0)

        game_index.add_parser_argument(group, '-g', '--game')
        if multiple_tags:
            group.add_argument('-t', '--tag', help='comma-separated tags for this run (e.g. "v1,v2")')
        else:
            group.add_argument('-t', '--tag', help='tag for this run (e.g. "v1")')
        group.add_argument('--output-dir', default=default_output_dir,
                           help=f'alphazero directory (default: ${env_var}=%(default)s)')

    def add_to_cmd(self, cmd: List[str]):
        env_var = 'A0A_OUTPUT_DIR'
        default_output_dir = os.environ[env_var]

        if default_output_dir != self.output_dir:
            cmd.append('--output-dir')
            cmd.append(self.output_dir)

        cmd.extend([
            '--game', self.game,
            '--tag', self.tag,
        ])
