// source: mcts.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.MCTS.Child', null, global);
goog.exportSymbol('proto.MCTS.GameSubtree', null, global);
goog.exportSymbol('proto.MCTS.GameTree', null, global);
goog.exportSymbol('proto.MCTS.Move', null, global);
goog.exportSymbol('proto.MCTS.Visit', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MCTS.Child = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MCTS.Child, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MCTS.Child.displayName = 'proto.MCTS.Child';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MCTS.Visit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MCTS.Visit.repeatedFields_, null);
};
goog.inherits(proto.MCTS.Visit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MCTS.Visit.displayName = 'proto.MCTS.Visit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MCTS.GameSubtree = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MCTS.GameSubtree.repeatedFields_, null);
};
goog.inherits(proto.MCTS.GameSubtree, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MCTS.GameSubtree.displayName = 'proto.MCTS.GameSubtree';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MCTS.Move = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MCTS.Move.repeatedFields_, null);
};
goog.inherits(proto.MCTS.Move, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MCTS.Move.displayName = 'proto.MCTS.Move';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MCTS.GameTree = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MCTS.GameTree.repeatedFields_, null);
};
goog.inherits(proto.MCTS.GameTree, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MCTS.GameTree.displayName = 'proto.MCTS.GameTree';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MCTS.Child.prototype.toObject = function(opt_includeInstance) {
  return proto.MCTS.Child.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MCTS.Child} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.Child.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, ""),
    rp: jspb.Message.getFieldWithDefault(msg, 2, ""),
    p: jspb.Message.getFieldWithDefault(msg, 3, ""),
    dir: jspb.Message.getFieldWithDefault(msg, 4, ""),
    v: jspb.Message.getFieldWithDefault(msg, 5, ""),
    n: jspb.Message.getFieldWithDefault(msg, 6, ""),
    e: jspb.Message.getFieldWithDefault(msg, 7, ""),
    puct: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MCTS.Child}
 */
proto.MCTS.Child.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MCTS.Child;
  return proto.MCTS.Child.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MCTS.Child} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MCTS.Child}
 */
proto.MCTS.Child.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRp(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setP(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDir(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setV(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setN(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setE(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPuct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MCTS.Child.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MCTS.Child.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MCTS.Child} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.Child.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRp();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getP();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDir();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getV();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getN();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getE();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPuct();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string action = 1;
 * @return {string}
 */
proto.MCTS.Child.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setAction = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string rP = 2;
 * @return {string}
 */
proto.MCTS.Child.prototype.getRp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setRp = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string P = 3;
 * @return {string}
 */
proto.MCTS.Child.prototype.getP = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setP = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string dir = 4;
 * @return {string}
 */
proto.MCTS.Child.prototype.getDir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setDir = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string V = 5;
 * @return {string}
 */
proto.MCTS.Child.prototype.getV = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setV = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string N = 6;
 * @return {string}
 */
proto.MCTS.Child.prototype.getN = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setN = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string E = 7;
 * @return {string}
 */
proto.MCTS.Child.prototype.getE = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setE = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string PUCT = 8;
 * @return {string}
 */
proto.MCTS.Child.prototype.getPuct = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Child} returns this
 */
proto.MCTS.Child.prototype.setPuct = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MCTS.Visit.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MCTS.Visit.prototype.toObject = function(opt_includeInstance) {
  return proto.MCTS.Visit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MCTS.Visit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.Visit.toObject = function(includeInstance, msg) {
  var f, obj = {
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.MCTS.Child.toObject, includeInstance),
    player: jspb.Message.getFieldWithDefault(msg, 2, ""),
    depth: jspb.Message.getFieldWithDefault(msg, 3, ""),
    board: jspb.Message.getFieldWithDefault(msg, 4, ""),
    eval: jspb.Message.getFieldWithDefault(msg, 5, ""),
    valueAvg: jspb.Message.getFieldWithDefault(msg, 6, ""),
    leaf: jspb.Message.getFieldWithDefault(msg, 7, ""),
    action: jspb.Message.getFieldWithDefault(msg, 8, ""),
    terminal: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MCTS.Visit}
 */
proto.MCTS.Visit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MCTS.Visit;
  return proto.MCTS.Visit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MCTS.Visit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MCTS.Visit}
 */
proto.MCTS.Visit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MCTS.Child;
      reader.readMessage(value,proto.MCTS.Child.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayer(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDepth(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBoard(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEval(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setValueAvg(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLeaf(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setTerminal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MCTS.Visit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MCTS.Visit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MCTS.Visit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.Visit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MCTS.Child.serializeBinaryToWriter
    );
  }
  f = message.getPlayer();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDepth();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBoard();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEval();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getValueAvg();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLeaf();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getTerminal();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * repeated Child children = 1;
 * @return {!Array<!proto.MCTS.Child>}
 */
proto.MCTS.Visit.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.MCTS.Child>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MCTS.Child, 1));
};


/**
 * @param {!Array<!proto.MCTS.Child>} value
 * @return {!proto.MCTS.Visit} returns this
*/
proto.MCTS.Visit.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MCTS.Child=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MCTS.Child}
 */
proto.MCTS.Visit.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MCTS.Child, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};


/**
 * optional string player = 2;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getPlayer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setPlayer = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string depth = 3;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getDepth = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setDepth = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string board = 4;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getBoard = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setBoard = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string eval = 5;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getEval = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setEval = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string value_avg = 6;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getValueAvg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setValueAvg = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string leaf = 7;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getLeaf = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setLeaf = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string action = 8;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setAction = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string terminal = 9;
 * @return {string}
 */
proto.MCTS.Visit.prototype.getTerminal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Visit} returns this
 */
proto.MCTS.Visit.prototype.setTerminal = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MCTS.GameSubtree.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MCTS.GameSubtree.prototype.toObject = function(opt_includeInstance) {
  return proto.MCTS.GameSubtree.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MCTS.GameSubtree} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.GameSubtree.toObject = function(includeInstance, msg) {
  var f, obj = {
    visitsList: jspb.Message.toObjectList(msg.getVisitsList(),
    proto.MCTS.Visit.toObject, includeInstance),
    i: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MCTS.GameSubtree}
 */
proto.MCTS.GameSubtree.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MCTS.GameSubtree;
  return proto.MCTS.GameSubtree.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MCTS.GameSubtree} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MCTS.GameSubtree}
 */
proto.MCTS.GameSubtree.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MCTS.Visit;
      reader.readMessage(value,proto.MCTS.Visit.deserializeBinaryFromReader);
      msg.addVisits(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setI(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MCTS.GameSubtree.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MCTS.GameSubtree.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MCTS.GameSubtree} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.GameSubtree.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVisitsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MCTS.Visit.serializeBinaryToWriter
    );
  }
  f = message.getI();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * repeated Visit visits = 1;
 * @return {!Array<!proto.MCTS.Visit>}
 */
proto.MCTS.GameSubtree.prototype.getVisitsList = function() {
  return /** @type{!Array<!proto.MCTS.Visit>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MCTS.Visit, 1));
};


/**
 * @param {!Array<!proto.MCTS.Visit>} value
 * @return {!proto.MCTS.GameSubtree} returns this
*/
proto.MCTS.GameSubtree.prototype.setVisitsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MCTS.Visit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MCTS.Visit}
 */
proto.MCTS.GameSubtree.prototype.addVisits = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MCTS.Visit, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MCTS.GameSubtree} returns this
 */
proto.MCTS.GameSubtree.prototype.clearVisitsList = function() {
  return this.setVisitsList([]);
};


/**
 * optional int32 i = 2;
 * @return {number}
 */
proto.MCTS.GameSubtree.prototype.getI = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.MCTS.GameSubtree} returns this
 */
proto.MCTS.GameSubtree.prototype.setI = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MCTS.Move.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MCTS.Move.prototype.toObject = function(opt_includeInstance) {
  return proto.MCTS.Move.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MCTS.Move} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.Move.toObject = function(includeInstance, msg) {
  var f, obj = {
    subtreesList: jspb.Message.toObjectList(msg.getSubtreesList(),
    proto.MCTS.GameSubtree.toObject, includeInstance),
    board: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MCTS.Move}
 */
proto.MCTS.Move.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MCTS.Move;
  return proto.MCTS.Move.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MCTS.Move} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MCTS.Move}
 */
proto.MCTS.Move.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MCTS.GameSubtree;
      reader.readMessage(value,proto.MCTS.GameSubtree.deserializeBinaryFromReader);
      msg.addSubtrees(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBoard(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MCTS.Move.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MCTS.Move.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MCTS.Move} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.Move.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSubtreesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MCTS.GameSubtree.serializeBinaryToWriter
    );
  }
  f = message.getBoard();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated GameSubtree subtrees = 1;
 * @return {!Array<!proto.MCTS.GameSubtree>}
 */
proto.MCTS.Move.prototype.getSubtreesList = function() {
  return /** @type{!Array<!proto.MCTS.GameSubtree>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MCTS.GameSubtree, 1));
};


/**
 * @param {!Array<!proto.MCTS.GameSubtree>} value
 * @return {!proto.MCTS.Move} returns this
*/
proto.MCTS.Move.prototype.setSubtreesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MCTS.GameSubtree=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MCTS.GameSubtree}
 */
proto.MCTS.Move.prototype.addSubtrees = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MCTS.GameSubtree, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MCTS.Move} returns this
 */
proto.MCTS.Move.prototype.clearSubtreesList = function() {
  return this.setSubtreesList([]);
};


/**
 * optional string board = 2;
 * @return {string}
 */
proto.MCTS.Move.prototype.getBoard = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.Move} returns this
 */
proto.MCTS.Move.prototype.setBoard = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MCTS.GameTree.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MCTS.GameTree.prototype.toObject = function(opt_includeInstance) {
  return proto.MCTS.GameTree.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MCTS.GameTree} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.GameTree.toObject = function(includeInstance, msg) {
  var f, obj = {
    movesList: jspb.Message.toObjectList(msg.getMovesList(),
    proto.MCTS.Move.toObject, includeInstance),
    player: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MCTS.GameTree}
 */
proto.MCTS.GameTree.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MCTS.GameTree;
  return proto.MCTS.GameTree.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MCTS.GameTree} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MCTS.GameTree}
 */
proto.MCTS.GameTree.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MCTS.Move;
      reader.readMessage(value,proto.MCTS.Move.deserializeBinaryFromReader);
      msg.addMoves(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MCTS.GameTree.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MCTS.GameTree.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MCTS.GameTree} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MCTS.GameTree.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMovesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MCTS.Move.serializeBinaryToWriter
    );
  }
  f = message.getPlayer();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated Move moves = 1;
 * @return {!Array<!proto.MCTS.Move>}
 */
proto.MCTS.GameTree.prototype.getMovesList = function() {
  return /** @type{!Array<!proto.MCTS.Move>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MCTS.Move, 1));
};


/**
 * @param {!Array<!proto.MCTS.Move>} value
 * @return {!proto.MCTS.GameTree} returns this
*/
proto.MCTS.GameTree.prototype.setMovesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MCTS.Move=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MCTS.Move}
 */
proto.MCTS.GameTree.prototype.addMoves = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MCTS.Move, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MCTS.GameTree} returns this
 */
proto.MCTS.GameTree.prototype.clearMovesList = function() {
  return this.setMovesList([]);
};


/**
 * optional string player = 2;
 * @return {string}
 */
proto.MCTS.GameTree.prototype.getPlayer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MCTS.GameTree} returns this
 */
proto.MCTS.GameTree.prototype.setPlayer = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.MCTS);
