# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mcts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmcts.proto\x12\x04MCTS\"j\n\x05\x43hild\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\n\n\x02rP\x18\x02 \x01(\t\x12\t\n\x01P\x18\x03 \x01(\t\x12\x0b\n\x03\x64ir\x18\x04 \x01(\t\x12\t\n\x01V\x18\x05 \x01(\t\x12\t\n\x01N\x18\x06 \x01(\t\x12\t\n\x01\x45\x18\x07 \x01(\t\x12\x0c\n\x04PUCT\x18\x08 \x01(\t\"\x83\x01\n\x05Visit\x12\x1d\n\x08\x63hildren\x18\x01 \x03(\x0b\x32\x0b.MCTS.Child\x12\x0e\n\x06player\x18\x02 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\t\x12\r\n\x05\x62oard\x18\x04 \x01(\t\x12\x0c\n\x04\x65val\x18\x05 \x01(\t\x12\x11\n\tvalue_avg\x18\x06 \x01(\t\x12\x0c\n\x04leaf\x18\x07 \x01(\t\"5\n\x0bGameSubtree\x12\x1b\n\x06visits\x18\x01 \x03(\x0b\x32\x0b.MCTS.Visit\x12\t\n\x01i\x18\x02 \x01(\x05\":\n\x04Move\x12#\n\x08subtrees\x18\x01 \x03(\x0b\x32\x11.MCTS.GameSubtree\x12\r\n\x05\x62oard\x18\x02 \x01(\t\"5\n\x08GameTree\x12\x19\n\x05moves\x18\x01 \x03(\x0b\x32\n.MCTS.Move\x12\x0e\n\x06player\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcts_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHILD._serialized_start=20
  _CHILD._serialized_end=126
  _VISIT._serialized_start=129
  _VISIT._serialized_end=260
  _GAMESUBTREE._serialized_start=262
  _GAMESUBTREE._serialized_end=315
  _MOVE._serialized_start=317
  _MOVE._serialized_end=375
  _GAMETREE._serialized_start=377
  _GAMETREE._serialized_end=430
# @@protoc_insertion_point(module_scope)
